FROM postgres:16.15-alpine@sha256:cf78e76683b9ca8c5733cbbdce6c9262b45b6767934dd0a95e671f9a0fc20685

RUN apk add --no-cache --upgrade \
        libcrypto3=3.5.9-r0 \
        libssl3=3.5.9-r0 \
        libuuid=2.42.3-r1 && \
    rm /usr/local/bin/gosu

USER postgres
